OVN_EXTERNAL_NETWORK_HOST_IP="172.16.1.10"
OVN_EXTERNAL_NETWORK_HOST_IP_V6="172:16:1::A"

OVN_EXTERNAL_NETWORK="PhyNet"

# OVN Gateway Router
GATEWAY_ROUTER=gw0
GATEWAY_ROUTER_PORT=gw0-outside

# OVN Router
ROUTER=lr0
ROUTER_GATEWAY_PORT=lr0-outside

# OVN Switches
SWITCH1=sw0
SWITCH2=sw1

# OVN Switch Ports
SWITCH1_PORT1=sw0-port1
SWITCH1_PORT2=sw0-port2
SWITCH2_PORT1=sw1-port1
